import { useEffect, useState } from "react";
import { RefreshCw, Users, CreditCard, Bot, Settings2 } from "lucide-react";
import { adminApi } from "../services/api";

const card = [["Users","users",Users],["AI Generations","generations",Bot],["Payments","payments",CreditCard]];
export default function Admin(){
 const [stats,setStats]=useState({}); const [users,setUsers]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [saving,setSaving]=useState(null);
 const load=async()=>{setLoading(true);setError("");try{const [d,u]=await Promise.all([adminApi.dashboard(),adminApi.users()]);setStats(d.data||{});setUsers(u.data?.users||[]);}catch(e){setError(e.response?.data?.message||"Failed to load admin data.");}finally{setLoading(false);}};
 useEffect(()=>{load()},[]);
 const update=async(u,field,value)=>{setSaving(u.id+field);try{const r=await adminApi.updateUser(u.id,{[field]:value});setUsers(xs=>xs.map(x=>x.id===u.id?r.data.user:x));}catch(e){alert(e.response?.data?.message||"Update failed");}finally{setSaving(null);}};
 return <div><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-violet-400">Administration</p><h1 className="mt-2 text-3xl font-black">Admin Dashboard</h1><p className="mt-2 text-sm text-slate-500">Live platform metrics and account controls.</p></div><button onClick={load} className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/10 px-4 py-3 text-sm hover:bg-white/10"><RefreshCw size={16} className={loading?'animate-spin':''}/>Refresh</button></div>{error&&<div className="mt-5 rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{card.map(([label,key,I])=><div className="glass rounded-2xl p-5" key={key}><div className="flex items-center justify-between"><p className="text-xs text-slate-500">{label}</p><I size={18} className="text-violet-300"/></div><p className="mt-2 text-3xl font-bold">{stats[key]??0}</p></div>)}</div><section className="glass mt-8 rounded-2xl p-5"><div className="flex items-center gap-2"><Settings2 size={18} className="text-violet-300"/><h2 className="font-semibold">User management</h2></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-xs text-slate-500"><tr><th className="pb-3">User</th><th>Role</th><th>Plan</th><th>Credits</th><th>Created</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-t border-white/5"><td className="py-4"><p className="font-medium">{u.name}</p><p className="text-xs text-slate-500">{u.email}</p></td><td><select value={u.role} disabled={saving===u.id+'role'} onChange={e=>update(u,'role',e.target.value)} className="rounded-lg border border-white/10 bg-slate-900 px-2 py-2"><option value="user">User</option><option value="admin">Admin</option></select></td><td><select value={u.plan} disabled={saving===u.id+'plan'} onChange={e=>update(u,'plan',e.target.value)} className="rounded-lg border border-white/10 bg-slate-900 px-2 py-2"><option value="free">Free</option><option value="pro">Pro</option><option value="premium">Premium</option></select></td><td><input type="number" min="0" value={u.credits} disabled={saving===u.id+'credits'} onChange={e=>update(u,'credits',Number(e.target.value))} className="w-28 rounded-lg border border-white/10 bg-slate-900 px-2 py-2"/></td><td className="text-xs text-slate-500">{u.created_at?new Date(u.created_at).toLocaleDateString():"—"}</td></tr>)}</tbody></table>{!users.length&&!loading&&<p className="py-10 text-center text-sm text-slate-500">No users found.</p>}</div></section></div>;
}
